In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
# Load the dataset
df_bcn = pd.read_csv('data/Barcelona_20k.csv', sep=',', engine='python')
df_renta = pd.read_csv('data/renta_media.csv', encoding='latin-1', sep=';')

In [35]:
df_bcn.head()

       ndvi      ndbi     mndwi  elevation  longitude   latitude
0  0.472652 -0.062942 -0.451608          7   2.083328  41.330094
1  0.020544 -0.078212 -0.044439         14   2.085214  41.330094
2  0.067115  0.132365 -0.257349          7   2.087101  41.330094
3  0.213815  0.004185 -0.381386         11   2.094916  41.330094
4  0.246105  0.081708 -0.355307          8   2.106774  41.330094

In [36]:
df_renta.head()

,Municipios,Distritos,Secciones,Indicadores de renta media y mediana,Periodo,Total
0,08001 Abrera,NaN,NaN,Renta neta media por persona,2023,16.682
1,08001 Abrera,0800101 Abrera distrito 01,NaN,Renta neta media por persona,2023,16.682
2,08001 Abrera,0800101 Abrera distrito 01,0800101001 Abrera sección 01001,Renta neta media por persona,2023,16.065
3,08001 Abrera,0800101 Abrera distrito 01,0800101002 Abrera sección 01002,Renta neta media por persona,2023,15.216
4,08001 Abrera,0800101 Abrera distrito 01,0800101003 Abrera sección 01003,Renta neta media por persona,2023,19.616